### ISSUE TITLE
Issue in starting the plugin application

### ISSUE THREAD

**Issue by kavipreetha** [elastic/generator-kibana-plugin#2]
My configuration's 
Elasticsearch -2.0.0
Kibana -4.2.1
Node version - v5.0.0
npm version - v3.4.1

Started my elasticsearch and kibana
And followed the steps given in Kibana Plugin Yeoman Generator - Getting Started
Created a  new plugin directory with yo kibana-plugin
and started using npm start
root@root:~/my-new-plugin$ npm start
it shows the following error

npm ERR! Linux 3.13.0-68-generic
npm ERR! argv "/usr/local/bin/node" "/usr/bin/npm" "start"
npm ERR! node v5.0.0
npm ERR! npm  v3.4.1

npm ERR! missing script: start
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     /home/guidanz-kavi/my-new-plugin/npm-debug.log

Found that the start script in missing in package.json. 
So started using the following command
root@root:~/my-new-plugin$ node index.js
But it's exiting.

Kindly advice me to get started with the plugin.

**Comment by kavipreetha** [comment]
We have to start using the following command gulp dev

**Comment by bwalsh** [comment]
@kavipreetha thank you for the hint.
- I followed the steps in `Getting Started`
- ran `gulp dev`  ( hit ctrl-c to exit )
- went to my kibana directory and entered `$npm start`  

![image](https://cloud.githubusercontent.com/assets/47808/11427685/cb780676-9419-11e5-8b4b-591e70941aa0.png)
