### ISSUE TITLE
Allow passing Kibana server command-line options with npm start

### ISSUE THREAD

**Issue by ChristinaLy** [elastic/generator-kibana-plugin#25]
2 issues found:
1. run command "npm start" after generate the plugin. It run kibana automatically, no need to  run command  "bin/kibana --dev" as described in README.md. see as following details:
   npm start
   
   > test_plugin@0.0.0 start /test/my-new-plugin
   > plugin-helpers start
   
   watching for changes  (109 files)
   managr    log   [02:32:17.819] [info][listening] basePath Proxy running at https://localhost:5601/vgb
   optmzr    log   [02:32:20.793] [info][optimize] Lazy optimization of bundles for test_plugin, kibana and statusPage ready
   optmzr    log   [02:32:20.829] [info][optimize] Lazy optimization started
   optmzr    log   [02:32:20.856] [info] Plugin initialization disabled.
   server    log   [02:32:20.895] [info][optimize] Waiting for optimizer completion
   server    log   [02:32:20.929] [info][status][plugin:kibana] Status changed from uninitialized to green - Ready
   server    log   [02:32:20.976] [info][status][plugin:elasticsearch] Status changed from uninitialized to yellow - Waiting for Elasticsearch
   server    log   [02:32:20.998] [info][status][plugin:test_plugin] Status changed from uninitialized to green - Ready
   server    log   [02:32:21.003] [info][status][plugin:devMode] Status changed from uninitialized to green - Ready
   server    log   [02:32:21.015] [info][status][plugin:kbn_doc_views] Status changed from uninitialized to green - Ready
   server    log   [02:32:21.023] [info][status][plugin:kbn_vislib_vis_types] Status changed from uninitialized to green - Ready
   server    log   [02:32:21.027] [info][status][plugin:markdown_vis] Status changed from uninitialized to green - Ready
   server    log   [02:32:21.044] [info][status][plugin:metric_vis] Status changed from uninitialized to green - Ready
   server    log   [02:32:21.050] [info][status][plugin:spyModes] Status changed from uninitialized to green - Ready
   server    log   [02:32:21.055] [info][status][plugin:statusPage] Status changed from uninitialized to green - Ready
   server    log   [02:32:21
   .062] [info][status][plugin:elasticsearch] Status changed from yellow to green - Kibana index ready
   server    log   [02:32:21.064] [info][status][plugin:table_vis] Status changed from uninitialized to green - Ready
   server    log   [02:32:21.076] [info][status][plugin:testsBundle] Status changed from uninitialized to green - Ready
   server    log   [02:32:21.088] [info][listening] Server running at https://localhost:5603
   optmzr    log   [02:33:45.058] [info][optimize] Lazy optimization success in 84.22 seconds
2. Based on the situation described above, I can not start kibana without enabling ssl. to work around this issue, i just changed the code in: my-new-plugin/node_modules/@elastic/plugin-helpers/tasks/start.js, add a parameter '--no-ssl':
   var args = ['--dev', '--no-ssl', '--plugin-path', plugin.root];

reference: https://github.com/elastic/kibana/blob/master/CONTRIBUTING.md
When Kibana runs in development mode it will automatically use bundled SSL certificates.

My suggestion is: add a parameter --no-ssl when run command "npm start" in the my plugin directory to keep consistent with kibana.

**Comment by lukasolson** [comment]
You can accomplish this by running `npm start -- --no-ssl`.

**Comment by lukasolson** [comment]
JK, that's not true.

**Comment by spalger** [comment]
This is now possible, just as lucas said:

``` sh
npm start -- --no-ssl
```
