### ISSUE TITLE
Add Kibana version dependency in the readme

### ISSUE THREAD

**Issue by gmoskovicz** [elastic/generator-kibana-plugin#26]
Currently there is no way to know which version of Kibana is needed for this. It will be great to add the version at the Readme.

**Comment by petmakris** [comment]
+1

Would not work for kibana 4.2.x

**Comment by MichaelNeas** [comment]
It helps to have the development version of kibana, currently 6.0.0-alpha1 from master.  Once you clone your own development version you can change kibana's version inside of its package.json to reflect what version of elasticsearch to use

**Comment by w33ble** [comment]
There's a compatibility chart in there now, as of bfc649f
