### ISSUE TITLE
Shipped version of plugin generator should match shipped version of Kibana

### ISSUE THREAD

**Issue by rashidkpc** [elastic/generator-kibana-plugin#29]
Right now the plugin generator only supports Kibana master and there's no obvious way to only use 4.4 supported features. We shouldn't release a plugin generator that requires a version of Kibana we haven't released.

**Comment by spalger** [comment]
I think this is resolved now that Kibana 5.0 is released.

We have also improved the tooling a bit to ask which kibana version you want to write for (only listing options for supported version) and if you choose `master` then the build script will ask you which kibana version you are building when you build.

**Comment by spalger** [comment]
We are also mostly matching the elastic stack version now
