### ISSUE TITLE
do we support kibana5?

### ISSUE THREAD

**Issue by xycloud** [elastic/generator-kibana-plugin#31]
do we support kibana5?

**Comment by jatanpatel92** [comment]
Yes, but since kibana5 is in alpha testing and have some issues including blocker currently, try some stable version of kibana as of now. As you are developing a plugin, it should be easier to install it in latest versions.

**Comment by rashidkpc** [comment]
Depends what you mean by "support". The plugin generator works with the Kibana 5 alpha snapshots, but of course Kibana 5 isn't formally supported by elastic until GA.
