### ISSUE TITLE
Generated plugins fail on Kibana master

### ISSUE THREAD

**Issue by aleph-zero** [elastic/generator-kibana-plugin#35]
Using master branches of both `generator-kibana-plugin` and `kibana`, when generating a new plugin you will get a failure

```
TypeError: _uiChrome2['default'].setNavBackground('#222222').setTabs is not a function. (In '_uiChrome2['default'].setNavBackground('#222222').setTabs([])', '_uiChrome2['default'].setNavBackground('#222222').setTabs' is undefined)
```

**Comment by gspkibana** [comment]
I get the same error:
"TypeError: _uiChrome2.default.setNavBackground(...).setTabs is not a function (http://<url>:5601/bundles/isi_disk_usage.bundle.js?v=13499:1)"

"Version: 5.0.0-alpha5
Build: 13499

Error: TypeError: _uiChrome2.default.setNavBackground(...).setTabs is not a function (http://<url>:5601/bundles/isi_disk_usage.bundle.js?v=13499:1)
window.onerror@http://<url>:5601/bundles/commons.bundle.js?v=13499:67:4639
"

**Comment by lukasolson** [comment]
Is this still happening? I'm not able to reproduce this.

**Comment by spalger** [comment]
Pretty sure this was fixed
