### ISSUE TITLE
How to bootstrap existing kibana plugin source code that is not generated by yeoman?

### ISSUE THREAD

**Issue by s101d1** [elastic/generator-kibana-plugin#41]
If I have a kibana plugin source code folder that is not generated by yeoman, is there a way to bootstrap it with the generator-kibana-plugin ?

**Comment by spalger** [comment]
Nope, but integrating the `@elastic/kibana-plugin-helpers` is probably a good start.

  - [dependency](https://github.com/elastic/generator-kibana-plugin/blob/master/src/generators/app/templates/package.json#L19)
  - [scripts](https://github.com/elastic/generator-kibana-plugin/blob/master/src/generators/app/templates/package.json#L10-L15)

**Comment by s101d1** [comment]
Thanks, it works.

I have another question, is it possible to tell the plugin it supports a major kibana version regardless of the minor version? e.g. I want to tell the plugin it's compatible with v5.0.x, so it would support kibana v5.0.0, 5.0.1, 5.0.2, etc.

Currently I have to define a specific kibana version in package.json:

```
  "kibana": {
    "version": "5.0.2"
  },
```

And another question, is generator-kibana-plugin able to support kibana v4 ? Because I don't see the v4 option when running `yo kibana-plugin`. I only see 5.0.0, 5.1.0, and 6.0.0.

**Comment by spalger** [comment]
Nope, sorry. We reserve the right to break APIs even in patch releases (for the time being) so we only allow publishing plugins for a single specific version. For development we support [using the "kibana" version](https://github.com/elastic/kibana/blob/master/src/core_plugins/elasticsearch/package.json#L3), but the installer won't install a plugin with the Kibana version. Also, there are older version of the plugin generator that support 4.x, but I'm not sure which ones, and they didn't support the plugin helpers.

**Comment by s101d1** [comment]
I found this in someone else code: https://github.com/fermiumlabs/mathlion/blob/master/package.json#L4-L9

```
  "kibanas": [
    "5.0.0-beta1",
    "5.0.0",
    "5.0.1",
    "5.0.2"
],
```

Is this way legit?

**Comment by spalger** [comment]
Hmm, I seem to remember hearing that that was in the works. Try it out and let me know :)

**Comment by s101d1** [comment]
It doesn't work unfortunately. The `kibanas` setting is not recognized by the plugin installer. Checking their codes, turns out the `kibanas` is just a hint field for gulp to generate all supported version package.json.
