### ISSUE TITLE
node version vs. npm install

### ISSUE THREAD

**Issue by srl295** [elastic/generator-kibana-plugin#46]
It seems like step `#1` in the README should come later. Step `#2` has you make sure your node version matches Kibana’s. Logically you want to run `nvm` before `npm install -g yo generator-kibana-plugin`. 

I suggest swapping step 1 and 2.

// cc @hickeyma 

PS: Made my first Kibana plugin!

**Comment by spalger** [comment]
😄  good suggestion

**Comment by srl295** [comment]
@spalger change in https://github.com/elastic/generator-kibana-plugin/commit/55a5d7da692ab93e20082cfac29c6dea91a12cce looks good! :+1:
