### ISSUE TITLE
describe minimal and advanced

### ISSUE THREAD

**Issue by srl295** [elastic/generator-kibana-plugin#47]
https://github.com/elastic/generator-kibana-plugin/blob/master/src/generators/app/index.js#L9

```
$ yo kibana-plugin --help
Usage:
  yo kibana-plugin:app [options] 

Options:
  -h,   --help          # Print the generator's options and usage
        --skip-cache    # Do not remember prompt answers             Default: false
        --skip-install  # Do not automatically install dependencies  Default: false
        --advanced      # Description for advanced
        --minimal       # Description for minimal
```

The  advanced and minimal options are missing descriptions. Perhaps as per http://yeoman.io/generator/Base.html#option

**Comment by spalger** [comment]
Hehe :)

**Comment by spalger** [comment]
Just pushed [v6.2.0](https://github.com/elastic/generator-kibana-plugin/releases/tag/v6.2.0) which adds descriptions for these flags (and deprecates the `--advanced` flag in favor of `--custom`)
