### ISSUE TITLE
How can I specify the app version?

### ISSUE THREAD

**Issue by sergibondarenko** [elastic/generator-kibana-plugin#50]
There are only three versions available:
```
rm -rf ../my-kibana-app/*
yo kibana-plugin
? Your Plugin Name myapp
? Short Description An app
? Target Kibana Version 
❯ master 
  6.0.0 
  5.1.0 
  5.0.0 
```

I tried 5.1.0 (I run Kibana 5.1.3) and now I see these warnings in the console:
```
optmzr    log   [12:39:24.526] [warning] Plugin "myapp" was disabled because it expected Kibana version "5.1.0", and found "5.1.3".
server    log   [12:39:24.587] [warning] Plugin "myapp" was disabled because it expected Kibana version "5.1.0", and found "5.1.3".
```

Plus, I don't see the app icon on the left bar:
![screenshot from 2017-05-16 14-43-10](https://cloud.githubusercontent.com/assets/5389745/26106391/1184fccc-3a46-11e7-835e-b91a28991f4d.png)

**Comment by w33ble** [comment]
Yeah, this seems like a bug in the generator. We currently [keep a list of available versions](https://github.com/elastic/generator-kibana-plugin/blob/master/src/generators/app/index.js#L80), which we clearly don't keep updated. 

That should probably just be a text entry.

@SergeyBondarenko you can set `kibana.version` or `version` in your package.json file, just make sure it matches the version of Kibana you are using (5.1.3 in your case).

**Comment by w33ble** [comment]
Since this generator has been replaced by [the template](https://github.com/elastic/template-kibana-plugin/), and the template just uses a text input, I'm going to close this.
