### ISSUE TITLE
Cannot access my plugin

### ISSUE THREAD

**Issue by ghost** [elastic/generator-kibana-plugin#52]
Hi! i have created a plugin through "yo kiabana-plugin" command , but when i try to access it in UI it gives me a fatal error, couldnot figure out the issue.
![capture](https://user-images.githubusercontent.com/29251534/27075620-53491518-5048-11e7-96a4-9a395f6636b9.PNG)

**Comment by w33ble** [comment]
This is with no modifications to the generator? What options did you pick?

**Comment by ghost** [comment]
i have just given name, description and version as 6.0.0, also i have tried by choosing lower versions and master but that gives the same fatal error

**Comment by w33ble** [comment]
So, just so I'm clear, you answered no when asked to generate an example app, translations, hack, and API?

**Comment by ghost** [comment]
i just followed this link: https://github.com/elastic/generator-kibana-plugin#getting-started
I got created the plugin with the name sraha...but when i click on the plugin i got fatal error which i mentioned before

**Comment by w33ble** [comment]
Oh, sorry, I thought the generator asked you questions about what to install. I was wrong. Just tried it locally and I get the same problem. I'll look into it. Sorry about all the questions.

**Comment by w33ble** [comment]
Published v7.0.0, which fixes this issue.

The problem was caused by the change to how `ui/modules` exports, see https://github.com/elastic/kibana/pull/11221.

**Comment by ghost** [comment]
sorry I didnt get you, can you please elaborate the details.....you mean i need to change the version of elastic search from v6.0.0 to 7?

**Comment by w33ble** [comment]
No, sorry. I pushed a version 7 of this generator, which works correctly now. 

If you rather not re-generate your project, you can fix your existing code by making the same change I made in [this commit](https://github.com/elastic/generator-kibana-plugin/commit/d2d805f913945d22fae64f76a39567f8bab17e94). `uiModules` needs to be destructured out of the import by name.
