### ISSUE TITLE
Overriding Translations using Kibana Plugin

### ISSUE THREAD

**Issue by iam-xtreme** [elastic/generator-kibana-plugin#58]
Cannot find a way to override the value for 'UI-WELCOME_MESSAGE' in en.json using custom kibana plugin translations.
Kindly guide me with this/

**Comment by w33ble** [comment]
Closing as a non-issue.

I don't personally know how translations work, and I don't think anyone that does is watching this repo. I encourage you to post questions on the Kibana forum at https://discuss.elastic.co/c/kibana.
